version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - aws-cli/install
      - checkout

      - run:
          name: Copying to S3
          command: aws s3 cp index.html s3://public.nikhil.io/index.html
