version: 2.1

jobs:
  build:
    docker:
      - image: afreeorange/build:latest

    steps:
      - checkout

      - run:
          name: Building
          command:
            inline-source --compress false --root ./ index.html > build.html

      - run:
          name: Copying to destinations in configs/
          command: |-
            for JSON_FILE in configs/*; do
                SITE="$(basename "${JSON_FILE%.json}")";

                aws s3 cp build.html s3://"$SITE"/index.html
                aws s3 cp configs/"$SITE".json s3://"$SITE"/s3-bucket-listing.config.json
            done
